SET NOCOUNT ON;
IF DB_ID(N'StatsGovCompatLabV132') IS NULL
    THROW 51456,'Compatibility lab database is missing.',1;
ALTER DATABASE [StatsGovCompatLabV132] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [StatsGovCompatLabV132];
SELECT N'COMPATIBILITY_LAB_CLEANUP_PASS' AS Status;
